### ISSUE TITLE
manifest.json written to wrong path

### ISSUE THREAD

**Issue by anitagraham** [nikushi/minipack#30]
Hi,

my Minipack.config looks like this:
```
Minipack.configuration do |c|
  c.cache = !Rails.env.development?
  c. manifest = Rails.root.join('public', 'assets', 'manifest.json')
  c.extract_css = false # not emitting css yet.
end
```

but  my manifest file ends up in `public/javascripts/`, which is the destination path for my webpack build.  I've been working around this in development mode, but I want to build for production now.

Any clues on what is happening?

Anita Graham

**Comment by Jukejc** [comment]
the `c.manifest` option is defining where minipack should read the generated webpack manifest from. 

For example, in order for minipack to read the manifest with your current setup, it should be 

`  c. manifest = Rails.root.join('public', 'javascripts', 'manifest.json')`

**Comment by nikushi** [comment]
Thank you @Jukejc :)
