### ISSUE TITLE
conflict with ransack

### ISSUE THREAD

**Issue by sadgb** [nikushi/minipack#31]
Hi. 
We've got conflict issue after adding ransack 2.3.0

![image](https://user-images.githubusercontent.com/661443/77109306-bc680a00-6a34-11ea-95cc-ed6c6614437a.png)

Here options_for will use options_for method from ransack helper 

![image](https://user-images.githubusercontent.com/661443/77109361-d0ac0700-6a34-11ea-8e54-70459a3383d3.png)

We are using latest version of minipack.

**Comment by nikushi** [comment]
Fixed in #32
